parsers:
- crowdsecurity/endlessh-logs
- crowdsecurity/dateparse-enrich
scenarios:
- crowdsecurity/endlessh-bf
postoverflows:
- ""
log_file: endlessh-logs.log
log_type: endlessh
ignore_parsers: false
