parsers:
- ./parsers/s01-parse/crowdsecurity/endlessh-logs
- crowdsecurity/dateparse-enrich
scenarios:
- ./scenarios/crowdsecurity/endlessh-bf
postoverflows:
- ""
log_file: endlessh-logs.log
log_type: endlessh
ignore_parsers: false
